services:
  mysql:
    image: mysql:latest
    container_name: rowgate-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rowgate
      MYSQL_DATABASE: rowgate_test
      MYSQL_USER: rowgate
      MYSQL_PASSWORD: rowgate
    ports:
      - "3307:3306"
